/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KarteRouteImport } from './routes/karte'
import { Route as EmbedInfoRouteImport } from './routes/embed-info'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KartenWindRouteImport } from './routes/karten.wind'
import { Route as KartenRegionRouteImport } from './routes/karten.region'
import { Route as KartenRadarRouteImport } from './routes/karten.radar'
import { Route as KartenPollenRouteImport } from './routes/karten.pollen'
import { Route as KartenLokalRouteImport } from './routes/karten.lokal'
import { Route as EmbedWindRouteImport } from './routes/embed.wind'
import { Route as EmbedRegionLokalRouteImport } from './routes/embed.region-lokal'
import { Route as EmbedRegionRouteImport } from './routes/embed.region'
import { Route as EmbedRadarRouteImport } from './routes/embed.radar'
import { Route as EmbedPollenRouteImport } from './routes/embed.pollen'
import { Route as EmbedLokalRouteImport } from './routes/embed.lokal'
import { Route as EmbedAllRouteImport } from './routes/embed.all'
import { Route as ApiPublicRadarIngestTriggerRouteImport } from './routes/api/public/radar/ingest-trigger'
import { Route as ApiPublicEpsIngestTriggerRouteImport } from './routes/api/public/eps/ingest-trigger'
import { Route as ApiPublicDebugR2CacheRouteImport } from './routes/api/public/debug/r2-cache'

const KarteRoute = KarteRouteImport.update({
  id: '/karte',
  path: '/karte',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedInfoRoute = EmbedInfoRouteImport.update({
  id: '/embed-info',
  path: '/embed-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KartenWindRoute = KartenWindRouteImport.update({
  id: '/karten/wind',
  path: '/karten/wind',
  getParentRoute: () => rootRouteImport,
} as any)
const KartenRegionRoute = KartenRegionRouteImport.update({
  id: '/karten/region',
  path: '/karten/region',
  getParentRoute: () => rootRouteImport,
} as any)
const KartenRadarRoute = KartenRadarRouteImport.update({
  id: '/karten/radar',
  path: '/karten/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const KartenPollenRoute = KartenPollenRouteImport.update({
  id: '/karten/pollen',
  path: '/karten/pollen',
  getParentRoute: () => rootRouteImport,
} as any)
const KartenLokalRoute = KartenLokalRouteImport.update({
  id: '/karten/lokal',
  path: '/karten/lokal',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedWindRoute = EmbedWindRouteImport.update({
  id: '/embed/wind',
  path: '/embed/wind',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRegionLokalRoute = EmbedRegionLokalRouteImport.update({
  id: '/embed/region-lokal',
  path: '/embed/region-lokal',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRegionRoute = EmbedRegionRouteImport.update({
  id: '/embed/region',
  path: '/embed/region',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRadarRoute = EmbedRadarRouteImport.update({
  id: '/embed/radar',
  path: '/embed/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedPollenRoute = EmbedPollenRouteImport.update({
  id: '/embed/pollen',
  path: '/embed/pollen',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedLokalRoute = EmbedLokalRouteImport.update({
  id: '/embed/lokal',
  path: '/embed/lokal',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedAllRoute = EmbedAllRouteImport.update({
  id: '/embed/all',
  path: '/embed/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRadarIngestTriggerRoute =
  ApiPublicRadarIngestTriggerRouteImport.update({
    id: '/api/public/radar/ingest-trigger',
    path: '/api/public/radar/ingest-trigger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEpsIngestTriggerRoute =
  ApiPublicEpsIngestTriggerRouteImport.update({
    id: '/api/public/eps/ingest-trigger',
    path: '/api/public/eps/ingest-trigger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDebugR2CacheRoute = ApiPublicDebugR2CacheRouteImport.update({
  id: '/api/public/debug/r2-cache',
  path: '/api/public/debug/r2-cache',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/embed-info': typeof EmbedInfoRoute
  '/karte': typeof KarteRoute
  '/embed/all': typeof EmbedAllRoute
  '/embed/lokal': typeof EmbedLokalRoute
  '/embed/pollen': typeof EmbedPollenRoute
  '/embed/radar': typeof EmbedRadarRoute
  '/embed/region': typeof EmbedRegionRoute
  '/embed/region-lokal': typeof EmbedRegionLokalRoute
  '/embed/wind': typeof EmbedWindRoute
  '/karten/lokal': typeof KartenLokalRoute
  '/karten/pollen': typeof KartenPollenRoute
  '/karten/radar': typeof KartenRadarRoute
  '/karten/region': typeof KartenRegionRoute
  '/karten/wind': typeof KartenWindRoute
  '/api/public/debug/r2-cache': typeof ApiPublicDebugR2CacheRoute
  '/api/public/eps/ingest-trigger': typeof ApiPublicEpsIngestTriggerRoute
  '/api/public/radar/ingest-trigger': typeof ApiPublicRadarIngestTriggerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/embed-info': typeof EmbedInfoRoute
  '/karte': typeof KarteRoute
  '/embed/all': typeof EmbedAllRoute
  '/embed/lokal': typeof EmbedLokalRoute
  '/embed/pollen': typeof EmbedPollenRoute
  '/embed/radar': typeof EmbedRadarRoute
  '/embed/region': typeof EmbedRegionRoute
  '/embed/region-lokal': typeof EmbedRegionLokalRoute
  '/embed/wind': typeof EmbedWindRoute
  '/karten/lokal': typeof KartenLokalRoute
  '/karten/pollen': typeof KartenPollenRoute
  '/karten/radar': typeof KartenRadarRoute
  '/karten/region': typeof KartenRegionRoute
  '/karten/wind': typeof KartenWindRoute
  '/api/public/debug/r2-cache': typeof ApiPublicDebugR2CacheRoute
  '/api/public/eps/ingest-trigger': typeof ApiPublicEpsIngestTriggerRoute
  '/api/public/radar/ingest-trigger': typeof ApiPublicRadarIngestTriggerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/embed-info': typeof EmbedInfoRoute
  '/karte': typeof KarteRoute
  '/embed/all': typeof EmbedAllRoute
  '/embed/lokal': typeof EmbedLokalRoute
  '/embed/pollen': typeof EmbedPollenRoute
  '/embed/radar': typeof EmbedRadarRoute
  '/embed/region': typeof EmbedRegionRoute
  '/embed/region-lokal': typeof EmbedRegionLokalRoute
  '/embed/wind': typeof EmbedWindRoute
  '/karten/lokal': typeof KartenLokalRoute
  '/karten/pollen': typeof KartenPollenRoute
  '/karten/radar': typeof KartenRadarRoute
  '/karten/region': typeof KartenRegionRoute
  '/karten/wind': typeof KartenWindRoute
  '/api/public/debug/r2-cache': typeof ApiPublicDebugR2CacheRoute
  '/api/public/eps/ingest-trigger': typeof ApiPublicEpsIngestTriggerRoute
  '/api/public/radar/ingest-trigger': typeof ApiPublicRadarIngestTriggerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/embed-info'
    | '/karte'
    | '/embed/all'
    | '/embed/lokal'
    | '/embed/pollen'
    | '/embed/radar'
    | '/embed/region'
    | '/embed/region-lokal'
    | '/embed/wind'
    | '/karten/lokal'
    | '/karten/pollen'
    | '/karten/radar'
    | '/karten/region'
    | '/karten/wind'
    | '/api/public/debug/r2-cache'
    | '/api/public/eps/ingest-trigger'
    | '/api/public/radar/ingest-trigger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/embed-info'
    | '/karte'
    | '/embed/all'
    | '/embed/lokal'
    | '/embed/pollen'
    | '/embed/radar'
    | '/embed/region'
    | '/embed/region-lokal'
    | '/embed/wind'
    | '/karten/lokal'
    | '/karten/pollen'
    | '/karten/radar'
    | '/karten/region'
    | '/karten/wind'
    | '/api/public/debug/r2-cache'
    | '/api/public/eps/ingest-trigger'
    | '/api/public/radar/ingest-trigger'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/embed-info'
    | '/karte'
    | '/embed/all'
    | '/embed/lokal'
    | '/embed/pollen'
    | '/embed/radar'
    | '/embed/region'
    | '/embed/region-lokal'
    | '/embed/wind'
    | '/karten/lokal'
    | '/karten/pollen'
    | '/karten/radar'
    | '/karten/region'
    | '/karten/wind'
    | '/api/public/debug/r2-cache'
    | '/api/public/eps/ingest-trigger'
    | '/api/public/radar/ingest-trigger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EmbedInfoRoute: typeof EmbedInfoRoute
  KarteRoute: typeof KarteRoute
  EmbedAllRoute: typeof EmbedAllRoute
  EmbedLokalRoute: typeof EmbedLokalRoute
  EmbedPollenRoute: typeof EmbedPollenRoute
  EmbedRadarRoute: typeof EmbedRadarRoute
  EmbedRegionRoute: typeof EmbedRegionRoute
  EmbedRegionLokalRoute: typeof EmbedRegionLokalRoute
  EmbedWindRoute: typeof EmbedWindRoute
  KartenLokalRoute: typeof KartenLokalRoute
  KartenPollenRoute: typeof KartenPollenRoute
  KartenRadarRoute: typeof KartenRadarRoute
  KartenRegionRoute: typeof KartenRegionRoute
  KartenWindRoute: typeof KartenWindRoute
  ApiPublicDebugR2CacheRoute: typeof ApiPublicDebugR2CacheRoute
  ApiPublicEpsIngestTriggerRoute: typeof ApiPublicEpsIngestTriggerRoute
  ApiPublicRadarIngestTriggerRoute: typeof ApiPublicRadarIngestTriggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/karte': {
      id: '/karte'
      path: '/karte'
      fullPath: '/karte'
      preLoaderRoute: typeof KarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed-info': {
      id: '/embed-info'
      path: '/embed-info'
      fullPath: '/embed-info'
      preLoaderRoute: typeof EmbedInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karten/wind': {
      id: '/karten/wind'
      path: '/karten/wind'
      fullPath: '/karten/wind'
      preLoaderRoute: typeof KartenWindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karten/region': {
      id: '/karten/region'
      path: '/karten/region'
      fullPath: '/karten/region'
      preLoaderRoute: typeof KartenRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karten/radar': {
      id: '/karten/radar'
      path: '/karten/radar'
      fullPath: '/karten/radar'
      preLoaderRoute: typeof KartenRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karten/pollen': {
      id: '/karten/pollen'
      path: '/karten/pollen'
      fullPath: '/karten/pollen'
      preLoaderRoute: typeof KartenPollenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karten/lokal': {
      id: '/karten/lokal'
      path: '/karten/lokal'
      fullPath: '/karten/lokal'
      preLoaderRoute: typeof KartenLokalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/wind': {
      id: '/embed/wind'
      path: '/embed/wind'
      fullPath: '/embed/wind'
      preLoaderRoute: typeof EmbedWindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/region-lokal': {
      id: '/embed/region-lokal'
      path: '/embed/region-lokal'
      fullPath: '/embed/region-lokal'
      preLoaderRoute: typeof EmbedRegionLokalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/region': {
      id: '/embed/region'
      path: '/embed/region'
      fullPath: '/embed/region'
      preLoaderRoute: typeof EmbedRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/radar': {
      id: '/embed/radar'
      path: '/embed/radar'
      fullPath: '/embed/radar'
      preLoaderRoute: typeof EmbedRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/pollen': {
      id: '/embed/pollen'
      path: '/embed/pollen'
      fullPath: '/embed/pollen'
      preLoaderRoute: typeof EmbedPollenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/lokal': {
      id: '/embed/lokal'
      path: '/embed/lokal'
      fullPath: '/embed/lokal'
      preLoaderRoute: typeof EmbedLokalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/all': {
      id: '/embed/all'
      path: '/embed/all'
      fullPath: '/embed/all'
      preLoaderRoute: typeof EmbedAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radar/ingest-trigger': {
      id: '/api/public/radar/ingest-trigger'
      path: '/api/public/radar/ingest-trigger'
      fullPath: '/api/public/radar/ingest-trigger'
      preLoaderRoute: typeof ApiPublicRadarIngestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/eps/ingest-trigger': {
      id: '/api/public/eps/ingest-trigger'
      path: '/api/public/eps/ingest-trigger'
      fullPath: '/api/public/eps/ingest-trigger'
      preLoaderRoute: typeof ApiPublicEpsIngestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug/r2-cache': {
      id: '/api/public/debug/r2-cache'
      path: '/api/public/debug/r2-cache'
      fullPath: '/api/public/debug/r2-cache'
      preLoaderRoute: typeof ApiPublicDebugR2CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EmbedInfoRoute: EmbedInfoRoute,
  KarteRoute: KarteRoute,
  EmbedAllRoute: EmbedAllRoute,
  EmbedLokalRoute: EmbedLokalRoute,
  EmbedPollenRoute: EmbedPollenRoute,
  EmbedRadarRoute: EmbedRadarRoute,
  EmbedRegionRoute: EmbedRegionRoute,
  EmbedRegionLokalRoute: EmbedRegionLokalRoute,
  EmbedWindRoute: EmbedWindRoute,
  KartenLokalRoute: KartenLokalRoute,
  KartenPollenRoute: KartenPollenRoute,
  KartenRadarRoute: KartenRadarRoute,
  KartenRegionRoute: KartenRegionRoute,
  KartenWindRoute: KartenWindRoute,
  ApiPublicDebugR2CacheRoute: ApiPublicDebugR2CacheRoute,
  ApiPublicEpsIngestTriggerRoute: ApiPublicEpsIngestTriggerRoute,
  ApiPublicRadarIngestTriggerRoute: ApiPublicRadarIngestTriggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
