/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KarteRouteImport } from './routes/karte'
import { Route as EmbedInfoRouteImport } from './routes/embed-info'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KartenWindRouteImport } from './routes/karten.wind'
import { Route as KartenRegionRouteImport } from './routes/karten.region'
import { Route as KartenRadarRouteImport } from './routes/karten.radar'
import { Route as KartenNiederschlagRouteImport } from './routes/karten.niederschlag'
import { Route as KartenLokalRouteImport } from './routes/karten.lokal'
import { Route as InternIconsRouteImport } from './routes/intern.icons'
import { Route as EmbedWindRouteImport } from './routes/embed.wind'
import { Route as EmbedRegionLokalRouteImport } from './routes/embed.region-lokal'
import { Route as EmbedRegionRouteImport } from './routes/embed.region'
import { Route as EmbedRadarRouteImport } from './routes/embed.radar'
import { Route as EmbedLokalRouteImport } from './routes/embed.lokal'
import { Route as EmbedAllRouteImport } from './routes/embed.all'
import { Route as ApiPublicSymbolIngestTriggerRouteImport } from './routes/api/public/symbol/ingest-trigger'
import { Route as ApiPublicSnapshotMapRouteImport } from './routes/api/public/snapshot/$map'
import { Route as ApiPublicRadarIngestTriggerRouteImport } from './routes/api/public/radar/ingest-trigger'
import { Route as ApiPublicOpenmeteoIngestTriggerRouteImport } from './routes/api/public/openmeteo/ingest-trigger'
import { Route as ApiPublicMchIngestTriggerRouteImport } from './routes/api/public/mch/ingest-trigger'
import { Route as ApiPublicEmbedRegionLokalStaticRouteImport } from './routes/api/public/embed/region-lokal-static'
import { Route as ApiPublicDebugR2CacheRouteImport } from './routes/api/public/debug/r2-cache'
import { Route as ApiPublicAromeIngestTriggerRouteImport } from './routes/api/public/arome/ingest-trigger'

const KarteRoute = KarteRouteImport.update({
  id: '/karte',
  path: '/karte',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedInfoRoute = EmbedInfoRouteImport.update({
  id: '/embed-info',
  path: '/embed-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KartenWindRoute = KartenWindRouteImport.update({
  id: '/karten/wind',
  path: '/karten/wind',
  getParentRoute: () => rootRouteImport,
} as any)
const KartenRegionRoute = KartenRegionRouteImport.update({
  id: '/karten/region',
  path: '/karten/region',
  getParentRoute: () => rootRouteImport,
} as any)
const KartenRadarRoute = KartenRadarRouteImport.update({
  id: '/karten/radar',
  path: '/karten/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const KartenNiederschlagRoute = KartenNiederschlagRouteImport.update({
  id: '/karten/niederschlag',
  path: '/karten/niederschlag',
  getParentRoute: () => rootRouteImport,
} as any)
const KartenLokalRoute = KartenLokalRouteImport.update({
  id: '/karten/lokal',
  path: '/karten/lokal',
  getParentRoute: () => rootRouteImport,
} as any)
const InternIconsRoute = InternIconsRouteImport.update({
  id: '/intern/icons',
  path: '/intern/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedWindRoute = EmbedWindRouteImport.update({
  id: '/embed/wind',
  path: '/embed/wind',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRegionLokalRoute = EmbedRegionLokalRouteImport.update({
  id: '/embed/region-lokal',
  path: '/embed/region-lokal',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRegionRoute = EmbedRegionRouteImport.update({
  id: '/embed/region',
  path: '/embed/region',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRadarRoute = EmbedRadarRouteImport.update({
  id: '/embed/radar',
  path: '/embed/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedLokalRoute = EmbedLokalRouteImport.update({
  id: '/embed/lokal',
  path: '/embed/lokal',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedAllRoute = EmbedAllRouteImport.update({
  id: '/embed/all',
  path: '/embed/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSymbolIngestTriggerRoute =
  ApiPublicSymbolIngestTriggerRouteImport.update({
    id: '/api/public/symbol/ingest-trigger',
    path: '/api/public/symbol/ingest-trigger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSnapshotMapRoute = ApiPublicSnapshotMapRouteImport.update({
  id: '/api/public/snapshot/$map',
  path: '/api/public/snapshot/$map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRadarIngestTriggerRoute =
  ApiPublicRadarIngestTriggerRouteImport.update({
    id: '/api/public/radar/ingest-trigger',
    path: '/api/public/radar/ingest-trigger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOpenmeteoIngestTriggerRoute =
  ApiPublicOpenmeteoIngestTriggerRouteImport.update({
    id: '/api/public/openmeteo/ingest-trigger',
    path: '/api/public/openmeteo/ingest-trigger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMchIngestTriggerRoute =
  ApiPublicMchIngestTriggerRouteImport.update({
    id: '/api/public/mch/ingest-trigger',
    path: '/api/public/mch/ingest-trigger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmbedRegionLokalStaticRoute =
  ApiPublicEmbedRegionLokalStaticRouteImport.update({
    id: '/api/public/embed/region-lokal-static',
    path: '/api/public/embed/region-lokal-static',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDebugR2CacheRoute = ApiPublicDebugR2CacheRouteImport.update({
  id: '/api/public/debug/r2-cache',
  path: '/api/public/debug/r2-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAromeIngestTriggerRoute =
  ApiPublicAromeIngestTriggerRouteImport.update({
    id: '/api/public/arome/ingest-trigger',
    path: '/api/public/arome/ingest-trigger',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/embed-info': typeof EmbedInfoRoute
  '/karte': typeof KarteRoute
  '/embed/all': typeof EmbedAllRoute
  '/embed/lokal': typeof EmbedLokalRoute
  '/embed/radar': typeof EmbedRadarRoute
  '/embed/region': typeof EmbedRegionRoute
  '/embed/region-lokal': typeof EmbedRegionLokalRoute
  '/embed/wind': typeof EmbedWindRoute
  '/intern/icons': typeof InternIconsRoute
  '/karten/lokal': typeof KartenLokalRoute
  '/karten/niederschlag': typeof KartenNiederschlagRoute
  '/karten/radar': typeof KartenRadarRoute
  '/karten/region': typeof KartenRegionRoute
  '/karten/wind': typeof KartenWindRoute
  '/api/public/arome/ingest-trigger': typeof ApiPublicAromeIngestTriggerRoute
  '/api/public/debug/r2-cache': typeof ApiPublicDebugR2CacheRoute
  '/api/public/embed/region-lokal-static': typeof ApiPublicEmbedRegionLokalStaticRoute
  '/api/public/mch/ingest-trigger': typeof ApiPublicMchIngestTriggerRoute
  '/api/public/openmeteo/ingest-trigger': typeof ApiPublicOpenmeteoIngestTriggerRoute
  '/api/public/radar/ingest-trigger': typeof ApiPublicRadarIngestTriggerRoute
  '/api/public/snapshot/$map': typeof ApiPublicSnapshotMapRoute
  '/api/public/symbol/ingest-trigger': typeof ApiPublicSymbolIngestTriggerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/embed-info': typeof EmbedInfoRoute
  '/karte': typeof KarteRoute
  '/embed/all': typeof EmbedAllRoute
  '/embed/lokal': typeof EmbedLokalRoute
  '/embed/radar': typeof EmbedRadarRoute
  '/embed/region': typeof EmbedRegionRoute
  '/embed/region-lokal': typeof EmbedRegionLokalRoute
  '/embed/wind': typeof EmbedWindRoute
  '/intern/icons': typeof InternIconsRoute
  '/karten/lokal': typeof KartenLokalRoute
  '/karten/niederschlag': typeof KartenNiederschlagRoute
  '/karten/radar': typeof KartenRadarRoute
  '/karten/region': typeof KartenRegionRoute
  '/karten/wind': typeof KartenWindRoute
  '/api/public/arome/ingest-trigger': typeof ApiPublicAromeIngestTriggerRoute
  '/api/public/debug/r2-cache': typeof ApiPublicDebugR2CacheRoute
  '/api/public/embed/region-lokal-static': typeof ApiPublicEmbedRegionLokalStaticRoute
  '/api/public/mch/ingest-trigger': typeof ApiPublicMchIngestTriggerRoute
  '/api/public/openmeteo/ingest-trigger': typeof ApiPublicOpenmeteoIngestTriggerRoute
  '/api/public/radar/ingest-trigger': typeof ApiPublicRadarIngestTriggerRoute
  '/api/public/snapshot/$map': typeof ApiPublicSnapshotMapRoute
  '/api/public/symbol/ingest-trigger': typeof ApiPublicSymbolIngestTriggerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/embed-info': typeof EmbedInfoRoute
  '/karte': typeof KarteRoute
  '/embed/all': typeof EmbedAllRoute
  '/embed/lokal': typeof EmbedLokalRoute
  '/embed/radar': typeof EmbedRadarRoute
  '/embed/region': typeof EmbedRegionRoute
  '/embed/region-lokal': typeof EmbedRegionLokalRoute
  '/embed/wind': typeof EmbedWindRoute
  '/intern/icons': typeof InternIconsRoute
  '/karten/lokal': typeof KartenLokalRoute
  '/karten/niederschlag': typeof KartenNiederschlagRoute
  '/karten/radar': typeof KartenRadarRoute
  '/karten/region': typeof KartenRegionRoute
  '/karten/wind': typeof KartenWindRoute
  '/api/public/arome/ingest-trigger': typeof ApiPublicAromeIngestTriggerRoute
  '/api/public/debug/r2-cache': typeof ApiPublicDebugR2CacheRoute
  '/api/public/embed/region-lokal-static': typeof ApiPublicEmbedRegionLokalStaticRoute
  '/api/public/mch/ingest-trigger': typeof ApiPublicMchIngestTriggerRoute
  '/api/public/openmeteo/ingest-trigger': typeof ApiPublicOpenmeteoIngestTriggerRoute
  '/api/public/radar/ingest-trigger': typeof ApiPublicRadarIngestTriggerRoute
  '/api/public/snapshot/$map': typeof ApiPublicSnapshotMapRoute
  '/api/public/symbol/ingest-trigger': typeof ApiPublicSymbolIngestTriggerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/embed-info'
    | '/karte'
    | '/embed/all'
    | '/embed/lokal'
    | '/embed/radar'
    | '/embed/region'
    | '/embed/region-lokal'
    | '/embed/wind'
    | '/intern/icons'
    | '/karten/lokal'
    | '/karten/niederschlag'
    | '/karten/radar'
    | '/karten/region'
    | '/karten/wind'
    | '/api/public/arome/ingest-trigger'
    | '/api/public/debug/r2-cache'
    | '/api/public/embed/region-lokal-static'
    | '/api/public/mch/ingest-trigger'
    | '/api/public/openmeteo/ingest-trigger'
    | '/api/public/radar/ingest-trigger'
    | '/api/public/snapshot/$map'
    | '/api/public/symbol/ingest-trigger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/embed-info'
    | '/karte'
    | '/embed/all'
    | '/embed/lokal'
    | '/embed/radar'
    | '/embed/region'
    | '/embed/region-lokal'
    | '/embed/wind'
    | '/intern/icons'
    | '/karten/lokal'
    | '/karten/niederschlag'
    | '/karten/radar'
    | '/karten/region'
    | '/karten/wind'
    | '/api/public/arome/ingest-trigger'
    | '/api/public/debug/r2-cache'
    | '/api/public/embed/region-lokal-static'
    | '/api/public/mch/ingest-trigger'
    | '/api/public/openmeteo/ingest-trigger'
    | '/api/public/radar/ingest-trigger'
    | '/api/public/snapshot/$map'
    | '/api/public/symbol/ingest-trigger'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/embed-info'
    | '/karte'
    | '/embed/all'
    | '/embed/lokal'
    | '/embed/radar'
    | '/embed/region'
    | '/embed/region-lokal'
    | '/embed/wind'
    | '/intern/icons'
    | '/karten/lokal'
    | '/karten/niederschlag'
    | '/karten/radar'
    | '/karten/region'
    | '/karten/wind'
    | '/api/public/arome/ingest-trigger'
    | '/api/public/debug/r2-cache'
    | '/api/public/embed/region-lokal-static'
    | '/api/public/mch/ingest-trigger'
    | '/api/public/openmeteo/ingest-trigger'
    | '/api/public/radar/ingest-trigger'
    | '/api/public/snapshot/$map'
    | '/api/public/symbol/ingest-trigger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EmbedInfoRoute: typeof EmbedInfoRoute
  KarteRoute: typeof KarteRoute
  EmbedAllRoute: typeof EmbedAllRoute
  EmbedLokalRoute: typeof EmbedLokalRoute
  EmbedRadarRoute: typeof EmbedRadarRoute
  EmbedRegionRoute: typeof EmbedRegionRoute
  EmbedRegionLokalRoute: typeof EmbedRegionLokalRoute
  EmbedWindRoute: typeof EmbedWindRoute
  InternIconsRoute: typeof InternIconsRoute
  KartenLokalRoute: typeof KartenLokalRoute
  KartenNiederschlagRoute: typeof KartenNiederschlagRoute
  KartenRadarRoute: typeof KartenRadarRoute
  KartenRegionRoute: typeof KartenRegionRoute
  KartenWindRoute: typeof KartenWindRoute
  ApiPublicAromeIngestTriggerRoute: typeof ApiPublicAromeIngestTriggerRoute
  ApiPublicDebugR2CacheRoute: typeof ApiPublicDebugR2CacheRoute
  ApiPublicEmbedRegionLokalStaticRoute: typeof ApiPublicEmbedRegionLokalStaticRoute
  ApiPublicMchIngestTriggerRoute: typeof ApiPublicMchIngestTriggerRoute
  ApiPublicOpenmeteoIngestTriggerRoute: typeof ApiPublicOpenmeteoIngestTriggerRoute
  ApiPublicRadarIngestTriggerRoute: typeof ApiPublicRadarIngestTriggerRoute
  ApiPublicSnapshotMapRoute: typeof ApiPublicSnapshotMapRoute
  ApiPublicSymbolIngestTriggerRoute: typeof ApiPublicSymbolIngestTriggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/karte': {
      id: '/karte'
      path: '/karte'
      fullPath: '/karte'
      preLoaderRoute: typeof KarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed-info': {
      id: '/embed-info'
      path: '/embed-info'
      fullPath: '/embed-info'
      preLoaderRoute: typeof EmbedInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karten/wind': {
      id: '/karten/wind'
      path: '/karten/wind'
      fullPath: '/karten/wind'
      preLoaderRoute: typeof KartenWindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karten/region': {
      id: '/karten/region'
      path: '/karten/region'
      fullPath: '/karten/region'
      preLoaderRoute: typeof KartenRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karten/radar': {
      id: '/karten/radar'
      path: '/karten/radar'
      fullPath: '/karten/radar'
      preLoaderRoute: typeof KartenRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karten/niederschlag': {
      id: '/karten/niederschlag'
      path: '/karten/niederschlag'
      fullPath: '/karten/niederschlag'
      preLoaderRoute: typeof KartenNiederschlagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karten/lokal': {
      id: '/karten/lokal'
      path: '/karten/lokal'
      fullPath: '/karten/lokal'
      preLoaderRoute: typeof KartenLokalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern/icons': {
      id: '/intern/icons'
      path: '/intern/icons'
      fullPath: '/intern/icons'
      preLoaderRoute: typeof InternIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/wind': {
      id: '/embed/wind'
      path: '/embed/wind'
      fullPath: '/embed/wind'
      preLoaderRoute: typeof EmbedWindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/region-lokal': {
      id: '/embed/region-lokal'
      path: '/embed/region-lokal'
      fullPath: '/embed/region-lokal'
      preLoaderRoute: typeof EmbedRegionLokalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/region': {
      id: '/embed/region'
      path: '/embed/region'
      fullPath: '/embed/region'
      preLoaderRoute: typeof EmbedRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/radar': {
      id: '/embed/radar'
      path: '/embed/radar'
      fullPath: '/embed/radar'
      preLoaderRoute: typeof EmbedRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/lokal': {
      id: '/embed/lokal'
      path: '/embed/lokal'
      fullPath: '/embed/lokal'
      preLoaderRoute: typeof EmbedLokalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/all': {
      id: '/embed/all'
      path: '/embed/all'
      fullPath: '/embed/all'
      preLoaderRoute: typeof EmbedAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/symbol/ingest-trigger': {
      id: '/api/public/symbol/ingest-trigger'
      path: '/api/public/symbol/ingest-trigger'
      fullPath: '/api/public/symbol/ingest-trigger'
      preLoaderRoute: typeof ApiPublicSymbolIngestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/snapshot/$map': {
      id: '/api/public/snapshot/$map'
      path: '/api/public/snapshot/$map'
      fullPath: '/api/public/snapshot/$map'
      preLoaderRoute: typeof ApiPublicSnapshotMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radar/ingest-trigger': {
      id: '/api/public/radar/ingest-trigger'
      path: '/api/public/radar/ingest-trigger'
      fullPath: '/api/public/radar/ingest-trigger'
      preLoaderRoute: typeof ApiPublicRadarIngestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openmeteo/ingest-trigger': {
      id: '/api/public/openmeteo/ingest-trigger'
      path: '/api/public/openmeteo/ingest-trigger'
      fullPath: '/api/public/openmeteo/ingest-trigger'
      preLoaderRoute: typeof ApiPublicOpenmeteoIngestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mch/ingest-trigger': {
      id: '/api/public/mch/ingest-trigger'
      path: '/api/public/mch/ingest-trigger'
      fullPath: '/api/public/mch/ingest-trigger'
      preLoaderRoute: typeof ApiPublicMchIngestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/embed/region-lokal-static': {
      id: '/api/public/embed/region-lokal-static'
      path: '/api/public/embed/region-lokal-static'
      fullPath: '/api/public/embed/region-lokal-static'
      preLoaderRoute: typeof ApiPublicEmbedRegionLokalStaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug/r2-cache': {
      id: '/api/public/debug/r2-cache'
      path: '/api/public/debug/r2-cache'
      fullPath: '/api/public/debug/r2-cache'
      preLoaderRoute: typeof ApiPublicDebugR2CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/arome/ingest-trigger': {
      id: '/api/public/arome/ingest-trigger'
      path: '/api/public/arome/ingest-trigger'
      fullPath: '/api/public/arome/ingest-trigger'
      preLoaderRoute: typeof ApiPublicAromeIngestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EmbedInfoRoute: EmbedInfoRoute,
  KarteRoute: KarteRoute,
  EmbedAllRoute: EmbedAllRoute,
  EmbedLokalRoute: EmbedLokalRoute,
  EmbedRadarRoute: EmbedRadarRoute,
  EmbedRegionRoute: EmbedRegionRoute,
  EmbedRegionLokalRoute: EmbedRegionLokalRoute,
  EmbedWindRoute: EmbedWindRoute,
  InternIconsRoute: InternIconsRoute,
  KartenLokalRoute: KartenLokalRoute,
  KartenNiederschlagRoute: KartenNiederschlagRoute,
  KartenRadarRoute: KartenRadarRoute,
  KartenRegionRoute: KartenRegionRoute,
  KartenWindRoute: KartenWindRoute,
  ApiPublicAromeIngestTriggerRoute: ApiPublicAromeIngestTriggerRoute,
  ApiPublicDebugR2CacheRoute: ApiPublicDebugR2CacheRoute,
  ApiPublicEmbedRegionLokalStaticRoute: ApiPublicEmbedRegionLokalStaticRoute,
  ApiPublicMchIngestTriggerRoute: ApiPublicMchIngestTriggerRoute,
  ApiPublicOpenmeteoIngestTriggerRoute: ApiPublicOpenmeteoIngestTriggerRoute,
  ApiPublicRadarIngestTriggerRoute: ApiPublicRadarIngestTriggerRoute,
  ApiPublicSnapshotMapRoute: ApiPublicSnapshotMapRoute,
  ApiPublicSymbolIngestTriggerRoute: ApiPublicSymbolIngestTriggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
